# Application Name
spring.application.name=api-gateway

# Server Port Configuration
server.port=8765

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Spring Cloud Gateway Configuration
#spring.cloud.gateway.discovery.locator.enabled=true

# Enable route discovery for Gateway
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Actuator Configuration (Optional for Debugging)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
